services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: nest_app
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app_network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres_db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  db_logs:
